### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by mictadlo** [marbl/MHAP#15]
Hello,
I ran into `Unsupported major.minor version 52.0` while creating a bioconda [package](https://github.com/bioconda/bioconda-recipes/issues/3088#issuecomment-265554496). 

What could cause this problem with the 2.1.1 release?

Thank you in advance.

Mic

**Comment by skoren** [comment]
MHAP requires and is compiled with JDK8 so my guess is you're trying to run with an older version of Java.

**Comment by mictadlo** [comment]
Looking at the [output](https://github.com/bioconda/bioconda-recipes/issues/3088#issuecomment-265554496) below it sees uses JDK8, but it still fails somehow. Any idea what could I miss?

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mhap-2.1.1                 |                0         728 KB  local

The following NEW packages will be INSTALLED:

    java-jdk: 8.0.92-1 bioconda
    mhap:     2.1.1-0  local   

+ source /QRISdata/Q0231/apps/bin/activate /QRISdata/Q0231/apps/conda-bld/mhap_1480654640827/_t_env
+ /bin/bash -x -e /QRISdata/Q0231/apps/conda-bld/mhap_1480654640827/test_tmp/run_test.sh
+ mhap -h
+ grep -q MHAP:
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/umd/marbl/mhap/main/MhapMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
TESTS FAILED: mhap-2.1.1-0
```

**Comment by skoren** [comment]
Sorry, I didn't see your reply earlier. Hopefully you've resolved this issue already. 

Version 52.0 is JDK/JVK 8 so it was compiled with JDK8 but whatever JVM is running doesn't recognize this version. MHAP does not come with an ``mhap`` command, you would need to run ```java -jar mhap-2.1.1.jar``` (http://mhap.readthedocs.io/en/latest/quickstart.html) so the mhap script is being added by bioconda. I'm not sure how the run_test.sh is running or what the bioconda installation is doing. It is possible it is using a binary from another installation of the JVM (or a JVM vs JDK issue, javac is coming from JDK8 but java is coming from JVM1.7). Have you tried downloading the compiled MHAP release file and running with JDK 8 to see if it works. If it does, it is some issue in the bioconda distribution.
