### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress

### ISSUE THREAD

**Issue by juyouhui** [marbl/MHAP#9]
I used Pre-compiled jar file. When i run  "java  -Xmx70g -server -jar mhap-1.6.jar -s Ery_PacBio.full.fasta --pacbio-sensitive  --max-shift 0.1 --num-threads 24". It happened that. Need i to compiled from source code?

Processing files for storage in reverse index...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/bzip2/BZip2CompressorInputStream
        at edu.umd.marbl.mhap.impl.FastaData.<init>(Unknown Source)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.<init>(Unknown Source)
        at edu.umd.marbl.mhap.main.MhapMain.getSequenceHashStreamer(Unknown Source)
        at edu.umd.marbl.mhap.main.MhapMain.computeMain(Unknown Source)
        at edu.umd.marbl.mhap.main.MhapMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.bzip2.BZip2CompressorInputStream
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

**Comment by konstantinberlin** [comment]
Make sure you copy over the lib directory along with the jar file. You are missing the dependence library.

so directory should look like this
mhap-1.6.jar
./lib
./lib/<dependency1>.jar
...

**Comment by juyouhui** [comment]
Thanks, I see the directory  again, and find the extra  files.
